### ISSUE TITLE
All repos should not test everything against unrelated tests

### ISSUE THREAD

**Issue by lukehinds** [sigstore/community#121]
A lot of repos are running unit / integration tests against changes such as a markdown edit.

This causes unnecessary use of resources and not in the interest of sustainable computing. 

We should find some way to skip CI runs, perhaps based on extensions, .txt, .md

**Comment by lukehinds** [comment]
Something like this should do it:

```
on:
  push:
    paths-ignore:
      - '*.md'
      - 'docs/**'
```
